# Grid Interpolation


What's the fastest way to discretize continuous (x, y) or (x, y, z) coordinate data onto their nearest grid coordinates?

Said differently: what's the fastest way to turn the continuous, Euclidean position (6.778, 9.201) into a corresponding grid coordinate (7, 9) -- for example, the pixel coordinate in an image? Let's imagine I have 100 continuous (x, y) pairs and a known 150 x 150 discrete grid (e.g. 150^2 pairs of (0, 0), (1, 1), ..., etc. -- what's the fastest way to map each (x, y) pair to their nearest (grid1, grid2) coordinate?

Googling this didn't seem to give much results, but I'm sure this has been asked elsewhere, so apologies in advance if this is redundant.

https://stackoverflow.com/questions/62778939/python-fastest-way-to-map-continuous-coordinates-to-discrete-grid

### Manual method

In [74]:
grid_offset = np.array([0, 0]) # Where do you start
grid_spacing = np.array([0.1, 0.1]) # What's the space you consider (euclidian here)

# point in continuous coordinate space
(x1,y1) = (6.778, 9.201)
(x2,y2) = (1.8, 3.1)
(x3,y3) = (3.2, 9.01)
values = np.array([[x1,y1], [x2,y2], [x3,y3]])
print(values)

[[6.778 9.201]
 [1.8   3.1  ]
 [3.2   9.01 ]]


In [94]:
# Convert point to index
indexes = np.round((values - grid_offset)/grid_spacing).astype('int')
indexes

array([[68, 92],
       [18, 31],
       [32, 90]])

In [101]:
a = np.zeros((100,100))

In [103]:
a[indexes].shape

(3, 2, 100)

In [99]:
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [76]:
# Convert back index to grid coordiantes
print(grid_offset + indexes * grid_spacing)

[[6.8 9.2]
 [1.8 3.1]
 [3.2 9. ]]


### Scipy interpolate griddata

https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.griddata.html

In [28]:
from scipy.interpolate import griddata

In [78]:
(x1,y1) = (6.778, 9.201)
(x2,y2) = (1.8, 3.1)
(x3,y3) = (3.2, 9.01)
values = np.array([[x1,y1], [x2,y2], [x3,y3]])
values

array([[6.778, 9.201],
       [1.8  , 3.1  ],
       [3.2  , 9.01 ]])

In [79]:
griddata()

TypeError: griddata() missing 3 required positional arguments: 'points', 'values', and 'xi'

In [64]:
def func(x, y):
    return x+y

In [57]:
# Create a meshgrid
grid_x, grid_y = np.mgrid[0:10,0:10]

In [59]:
grid_x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [60]:
grid_y

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])