In [4]:
from minority_report.clean_data import CleanData
from minority_report.viz import Viz

from datetime import datetime

In [7]:
df = Viz()
df.load_data()

precinct_number                    offense_type crime_completed  \
0                     73  OFFENSES AGAINST PUBLIC ADMINI       COMPLETED   
1                     69    ASSAULT 3 & RELATED OFFENSES       COMPLETED   
2                     71                   HARRASSMENT 2       COMPLETED   
3                    112                            RAPE       COMPLETED   
4                     24                   GRAND LARCENY       COMPLETED   
...                  ...                             ...             ...   
6983202              109    ASSAULT 3 & RELATED OFFENSES       COMPLETED   
6983203               25   OFF. AGNST PUB ORD SENSBLTY &       COMPLETED   
6983204               41  CRIMINAL MISCHIEF & RELATED OF       COMPLETED   
6983205              107                          FRAUDS       COMPLETED   
6983206               67  GRAND LARCENY OF MOTOR VEHICLE       COMPLETED   

        offense_level premise_desc                     premise  \
0         MISDEMEANOR       INSIDE  RESIDENCE - PUBLIC HOUSING   
1         MISDEMEANOR       INSIDE             RESIDENCE-HOUSE   
2           VIOLATION       INSIDE               PUBLIC SCHOOL   
3              FELONY       INSIDE      RESIDENCE - APT. HOUSE   
4              FELONY       INSIDE       DOCTOR/DENTIST OFFICE   
...               ...          ...                         ...   
6983202   MISDEMEANOR       INSIDE      RESIDENCE - APT. HOUSE   
6983203   MISDEMEANOR       INSIDE      RESIDENCE - APT. HOUSE   
6983204        FELONY     FRONT OF                      STREET   
6983205   MISDEMEANOR       INSIDE      RESIDENCE - APT. HOUSE   
6983206        FELONY       INSIDE          STORE UNCLASSIFIED   

                jurisdiction park_name suspect_age    suspect_race  \
0        N.Y. HOUSING POLICE  NOT PARK       25-44           BLACK   
1           N.Y. POLICE DEPT  NOT PARK     UNKNOWN         UNKNOWN   
2           N.Y. POLICE DEPT  NOT PARK         <18           BLACK   
3           N.Y. POLICE DEPT  NOT PARK       25-44  WHITE HISPANIC   
4           N.Y. POLICE DEPT  NOT PARK     UNKNOWN         UNKNOWN   
...                      ...       ...         ...             ...   
6983202     N.Y. POLICE DEPT  NOT PARK       25-44  WHITE HISPANIC   
6983203     N.Y. POLICE DEPT  NOT PARK       25-44           BLACK   
6983204     N.Y. POLICE DEPT  NOT PARK     UNKNOWN         UNKNOWN   
6983205     N.Y. POLICE DEPT  NOT PARK     UNKNOWN         UNKNOWN   
6983206     N.Y. POLICE DEPT  NOT PARK     UNKNOWN         UNKNOWN   

        suspect_sex   latitude  longitude        metro victim_age  \
0                 M  40.664239 -73.908425  NOT SUBWAY         <18   
1           UNKNOWN  40.644590 -73.892672  NOT SUBWAY       45-64   
2                 M  40.658758 -73.942435  NOT SUBWAY       18-24   
3                 M  40.722364 -73.851474  NOT SUBWAY       25-44   
4           UNKNOWN  40.793465 -73.968950  NOT SUBWAY       45-64   
...             ...        ...        ...          ...        ...   
6983202           M  40.785050 -73.856852  NOT SUBWAY       25-44   
6983203           F  40.801717 -73.937283  NOT SUBWAY       25-44   
6983204     UNKNOWN  40.814612 -73.903637  NOT SUBWAY       25-44   
6983205           U  40.724699 -73.808549  NOT SUBWAY       18-24   
6983206     UNKNOWN  40.650987 -73.935263  NOT SUBWAY     UNKNOWN   

                      victim_race victim_sex               period    borough  \
0                           BLACK          M  2015-02-11 15:00:00   BROOKLYN   
1                           BLACK          F  2012-03-17 10:00:00   BROOKLYN   
2                           BLACK          M  2016-10-27 13:00:00   BROOKLYN   
3                           WHITE          F  2014-11-27 19:00:00     QUEENS   
4                           WHITE          F  2013-12-11 13:00:00  MANHATTAN   
...                           ...        ...                  ...        ...   
6983202  ASIAN / PACIFIC ISLANDER          F  2018-12-02 04:00:00     QUE

In [8]:
inf = df.data['period'] > datetime(2016, 10, 1, 0, 0, 0)
sup = df.data['period'] < datetime(2016, 10, 8, 0, 0, 0)
sample = df.data[ inf & sup ]

In [10]:
sample.head()

precinct_number                    offense_type crime_completed  \
117                13                   PETIT LARCENY       COMPLETED   
298                43                   PETIT LARCENY       COMPLETED   
312                28  CRIMINAL MISCHIEF & RELATED OF       COMPLETED   
804                14                   PETIT LARCENY       COMPLETED   
1571               26                   PETIT LARCENY       COMPLETED   

     offense_level premise_desc                 premise      jurisdiction  \
117    MISDEMEANOR       INSIDE             CHAIN STORE  N.Y. POLICE DEPT   
298    MISDEMEANOR     FRONT OF                  STREET  N.Y. POLICE DEPT   
312    MISDEMEANOR       INSIDE           PUBLIC SCHOOL  N.Y. POLICE DEPT   
804    MISDEMEANOR       INSIDE             CHAIN STORE  N.Y. POLICE DEPT   
1571   MISDEMEANOR       INSIDE  RESIDENCE - APT. HOUSE  N.Y. POLICE DEPT   

     park_name suspect_age suspect_race suspect_sex   latitude  longitude  \
117   NOT PARK       25-44        BLACK           M  40.739389 -73.991160   
298   NOT PARK     UNKNOWN      UNKNOWN           U  40.841560 -73.860970   
312   NOT PARK     UNKNOWN      UNKNOWN     UNKNOWN  40.806274 -73.951800   
804   NOT PARK     UNKNOWN      UNKNOWN     UNKNOWN  40.748831 -73.988478   
1571  NOT PARK     UNKNOWN      UNKNOWN           U  40.814865 -73.960204   

            metro victim_age               victim_race victim_sex  \
117   NOT SUBWAY     UNKNOWN                   UNKNOWN          D   
298   NOT SUBWAY         65+                     BLACK          M   
312   NOT SUBWAY     UNKNOWN                   UNKNOWN          D   
804   NOT SUBWAY       25-44            WHITE HISPANIC          F   
1571  NOT SUBWAY       18-24  ASIAN / PACIFIC ISLANDER          F   

                   period    borough         patrol_borough  
117   2016-10-05 10:00:00  MANHATTAN  PATROL BORO MAN SOUTH  
298   2016-10-01 13:00:00      BRONX      PATROL BORO BRONX  
312   2016-10-04 15:00:00  MANHATTAN  PATROL BORO MAN NORTH  
804   2016-10-07 16:00:00  MANHATTAN  PATROL BORO MAN SOUTH  
1571  2016-10-07 11:00:00  MANHATTAN  PATROL BORO MAN NORTH

In [12]:
type(sample['period'].iloc[0])

datetime.datetime

In [32]:
def round_six_hours(period):
    import ipdb ; ipdb.set_trace()
    if period.hour < 6:
        period.replace(hour=0)
    elif period.hour <12 :
        period.replace(hour=6)
    elif period.hour <18 :
        period.replace(hour=12)
    else:
        period.replace(hour=18)
    return period
    

In [30]:
sample['by_six_hour'] = sample['period'].apply(lambda x: round_six_hours(x))

<ipython-input-30-5787ff3f01db>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['by_six_hour'] = sample['period'].apply(lambda x: round_six_hours(x))


In [17]:
sample.head()

precinct_number                    offense_type crime_completed  \
117                13                   PETIT LARCENY       COMPLETED   
298                43                   PETIT LARCENY       COMPLETED   
312                28  CRIMINAL MISCHIEF & RELATED OF       COMPLETED   
804                14                   PETIT LARCENY       COMPLETED   
1571               26                   PETIT LARCENY       COMPLETED   

     offense_level premise_desc                 premise      jurisdiction  \
117    MISDEMEANOR       INSIDE             CHAIN STORE  N.Y. POLICE DEPT   
298    MISDEMEANOR     FRONT OF                  STREET  N.Y. POLICE DEPT   
312    MISDEMEANOR       INSIDE           PUBLIC SCHOOL  N.Y. POLICE DEPT   
804    MISDEMEANOR       INSIDE             CHAIN STORE  N.Y. POLICE DEPT   
1571   MISDEMEANOR       INSIDE  RESIDENCE - APT. HOUSE  N.Y. POLICE DEPT   

     park_name suspect_age suspect_race  ...  longitude        metro  \
117   NOT PARK       25-44        BLACK  ... -73.991160  NOT SUBWAY    
298   NOT PARK     UNKNOWN      UNKNOWN  ... -73.860970  NOT SUBWAY    
312   NOT PARK     UNKNOWN      UNKNOWN  ... -73.951800  NOT SUBWAY    
804   NOT PARK     UNKNOWN      UNKNOWN  ... -73.988478  NOT SUBWAY    
1571  NOT PARK     UNKNOWN      UNKNOWN  ... -73.960204  NOT SUBWAY    

      victim_age               victim_race victim_sex               period  \
117      UNKNOWN                   UNKNOWN          D  2016-10-05 10:00:00   
298          65+                     BLACK          M  2016-10-01 13:00:00   
312      UNKNOWN                   UNKNOWN          D  2016-10-04 15:00:00   
804        25-44            WHITE HISPANIC          F  2016-10-07 16:00:00   
1571       18-24  ASIAN / PACIFIC ISLANDER          F  2016-10-07 11:00:00   

        borough         patrol_borough           by_6_hour         by_six_hour  
117   MANHATTAN  PATROL BORO MAN SOUTH 2016-10-05 10:00:00 2016-10-05 10:00:00  
298       BRONX      PATROL BORO BRONX 2016-10-01 13:00:00 2016-10-01 13:00:00  
312   MANHATTAN  PATROL BORO MAN NORTH 2016-10-04 15:00:00 2016-10-04 15:00:00  
804   MANHATTAN  PATROL BORO MAN SOUTH 2016-10-07 16:00:00 2016-10-07 16:00:00  
1571  MANHATTAN  PATROL BORO MAN NORTH 2016-10-07 11:00:00 2016-10-07 11:00:00  

[5 rows x 22 columns]

In [33]:
round_six_hours(sample['period'].iloc[0])

> <ipython-input-32-e606d2e7921d>(3)round_six_hours()
      2     import ipdb ; ipdb.set_trace()
----> 3     if period.hour < 6:
      4         period.replace(hour=0)

ipdb> period.hour
10
ipdb> n
> <ipython-input-32-e606d2e7921d>(5)round_six_hours()
      4         period.replace(hour=0)
----> 5     elif period.hour <12 :
      6         period.replace(hour=6)

ipdb> period
datetime.datetime(2016, 10, 5, 10, 0)
ipdb> n
> <ipython-input-32-e606d2e7921d>(6)round_six_hours()
      5     elif period.hour <12 :
----> 6         period.replace(hour=6)
      7     elif period.hour <18 :

ipdb> period.hour
10
ipdb> n
> <ipython-input-32-e606d2e7921d>(11)round_six_hours()
     10         period.replace(hour=18)
---> 11     return period
     12 

ipdb> period.hour
10
ipdb> quit()


BdbQuit: 

In [38]:
a = np.array([[[1, 2, 3],[4, 5, 6]],[[7,8,9],[10,11,12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [39]:
a.shape

(2, 2, 3)

In [40]:
y = a.flatten()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
y.reshape((2,2,3))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])